# Author: TK
# Date: 23-01-2026
# Description: This is a cli for mini soc proj.
# It does the following tasks:
# Parsing cli args, Loads config file, Initialize detection rules,
# Process packets extracted from PCAP file
# Collecting alerts generated by rules
# Print alerts to console
# Save alerts to JSON file
# To execute : python -m mini_soc.cli --pcap sample.pcap --config config.yaml --out alerts.json

from __future__ import annotations
import argparse
import yaml
from typing import List

# Internal proj imports
from .capture import events_from_pcap
from .models import Alert
from .reporter import save_alerts_json
from .rules.port_scan import PortScanRule

def load_config(path: str):
    """Load the YAML config file
       Returns parsed config dict, empty dict if file is empty."""

    with open(path, "r", encoding = "utf-8") as file:
        return yaml.safe_load(file) or {}


def main():
    """Main CLI
       Responsibilities:
       - Parses cli args
       - Load config
       - Initialize detection rules
       - Process PCAP events
       - Collect and report alerts"""

    # Arg parsing
    ap = argparse.ArgumentParser(prog="Mini_SOC")
    ap.add_argument("--pcap", required=True, help="Path to .pcap file")
    ap.add_argument("--config", default="config.yaml", help="Path to config.yaml")
    ap.add_argument("--out", default="alerts.json", help="Output JSON report path")
    args = ap.parse_args()

    # load config
    cfg = load_config(args.config)
    rules_cfg = cfg.get("rules", {})

    # extract rule specific config
    rules = [
        PortScanRule(rules_cfg.get("port_scan", {}))

    ]

    # alert collection
    alerts: List[Alert] = []

    # process ev from PCAP
    for ev in events_from_pcap(args.pcap):
        for rule in rules:
            alerts.extend(rule.process(ev))

    # print formatted alerts
    for a in alerts:
        print(f"[{a.severity.upper()}] {a.rule_id} {a.title} :: {a.description}")

    # ALWAYS save output, even if empty
    save_alerts_json(alerts, args.out)
    print(f"\nSaved {len(alerts)} alerts to {args.out}")

if __name__ == "__main__":
    main()


